import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

public class MD5 {
	
	public static void main(String args[]) throws NoSuchAlgorithmException 
    { 
        String s = "trustpilot wants you"; 
        String HashValue = "e4820b45d2277f3844eac66c903e84be";
        System.out.println("Your HashCode Generated by MD5 is: " + getMd5(s)); 
    } 
	public static String getMd5(String input) 
    { 
        try { 
        	
            MessageDigest md = MessageDigest.getInstance("MD5"); 
            byte[] messageDigest = md.digest(input.getBytes()); 
  
            BigInteger no = new BigInteger(1, messageDigest); 
 
            String hashtext = no.toString(16); 
            while (hashtext.length() < 32) { 
                hashtext = "0" + hashtext; 
            } 
            return hashtext; 
        }  
  
        // For specifying wrong message digest algorithms 
        catch (NoSuchAlgorithmException e) { 
            throw new RuntimeException(e); 
        } 
    } 
  
}
